
export const FETCHED_LOGGED_USER = 'FETCHED_LOGGED_USER'
export const TYPE_USERNAME = 'TYPE_USERNAME'
export const TYPE_PASSWORD = 'TYPE_PASSWORD'
export const FETCHED_REGISTER_USER = 'FETCHED_REGISTER_USER'
export const TYPE_DETAILS = 'TYPE_DETAILS'
export const FETCHED_ERROR_USER = 'FETCHED_ERROR_USER'
export const TYPE_DEPOSIT_DETAILS = "TYPE_DEPOSIT_DETAILS"
export const TYPE_NEW_ACCOUNT_DETAILS = "TYPE_NEW_ACCOUNT_DETAILS"
export const TYPE_LOAN_DETAILS = "TYPE_LOAN_DETAILS"
